
var bossList = [
	{
		"id":"boss001",
		"name_en":"giant rat",
		"name":"거대한 쥐",
		"cardid":47366,
		"cardid_original":47366,
		"health":10,
		"stage":[1],
		"weight":1,
		"desc":"젊은 모험가 모두의 골칫거리입니다.",
		"power":"(2) 찍찍: 1/1 쥐를 2마리 소환합니다."
	}, 
	{
		"id":"boss002",
		"name_en":"wee whelp",
		"name":"작은 새끼용",
		"cardid":47309,
		"cardid_original":47309,
		"health":10,
		"stage":[1],
		"weight":1,
		"desc":"아기 용입니다. 그래도 용은 용이지요.",
		"power":"(2) 아기 숨결: 피해를 2 줍니다."
	}, 
	{
		"id":"boss003",
		"name_en":"bink the burglar",
		"name":"좀도둑 빙크",
		"cardid":47316,
		"cardid_original":47316,
		"health":10,
		"stage":[1],
		"weight":0.5,
		"desc":"막 여정을 시작한 모험가를 노리는 비열한 도둑입니다.",
		"power":"(0) 동전: 이번 턴에만 마나 수정을 1개 획득합니다."
	}, 
	{
		"id":"boss004",
		"name_en":"overseer mogark",
		"name":"감독관 모가르크",
		"cardid":46311,
		"cardid_original":46311,
		"health":20,
		"stage":[2,3],
		"weight":1,
		"desc":"부하들에게 지나친 \"동기부여\"를 하는 트로그 사령관입니다.",
		"power":"(1) 가혹한 말: 아군 하수인 하나에게 피해를 1 주고 공격력을 +2 부여합니다."
	}, 
	{
		"id":"boss005",
		"name_en":"frostfur",
		"name":"서리가죽",
		"cardid":46915,
		"cardid_original":46915,
		"health":20,
		"stage":[2,3],
		"weight":1,
		"desc":"이 펄볼그의 소굴은 이상하리만큼 춥습니다…",
		"power":"(2) 빙결: 하수인 하나를 빙결 상태로 만듭니다."
	}, 
	{
		"id":"boss006",
		"name_en":"graves the cleric",
		"name":"성직자 그레이브스",
		"cardid":46310,
		"cardid_original":46310,
		"health":20,
		"stage":[2,3],
		"weight":1,
		"desc":"오랜 시간 함께한 일행과 떨어진 치유사입니다.",
		"power":"(0) 빛의 의지: 모든 하수인의 생명력을 2 회복시킵니다."
	}, 
	{
		"id":"boss007",
		"name_en":"seriona",
		"name":"세리오나",
		"cardid":47261,
		"cardid_original":47261,
		"health":20,
		"stage":[2,3],
		"weight":1,
		"tog":"바보 황혼 용용이가 코볼트 약하게 만든다! 더, 약하게!",
		"desc":"당신의 하수인들을 흡수하려 하는 황혼의 용입니다.",
		"power":"(2) 쇠퇴의 빛: 하수인 하나에게 공격력을 -1 부여합니다."
	}, 
	{
		"id":"boss008",
		"name_en":"elder brandlemar",
		"name":"장로 덩굴가시",
		"cardid":46357,
		"cardid_original":46357,
		"health":20,
		"stage":[2,3],
		"weight":1,
		"desc":"마법사들 사이에서 악명이 높은 이 펄볼그는 어떤 주문이든 차단할 수 있습니다.",
		"power":"(2) 마법 감쇠: '마법 차단' 비밀 카드 1장을 사용합니다."
	}, 
	{
		"id":"boss009",
		"name_en":"candlebeard",
		"name":"촛불수염",
		"cardid":46317,
		"cardid_original":46317,
		"health":20,
		"stage":[2,3],
		"weight":1,
		"tog":"촛불수염은 보물 찾으면 코볼트가 해적이 될 줄 알고 있다.",
		"desc":"이 코볼트 해적이 가장 좋아하는 가수는 전진이라고 하네요.",
		"power":"(1) 돌진!: 하수인 하나에게 돌진을 부여합니다."
	}, 
	{
		"id":"boss010",
		"name_en":"pathmaker hamm",
		"name":"폭탄마 햄",
		"cardid":46269,
		"cardid_original":46269,
		"health":20,
		"stage":[2,3],
		"weight":1,
		"desc":"코볼트가 땅굴을 파는 방법은 한 가지가 아닙니다.",
		"power":"(1) 불안정한 폭발: 무작위 적 둘에게 피해를 1 줍니다."
	}, 
	{
		"id":"boss011",
		"name_en":"waxmancer sturmi",
		"name":"밀랍술사 스터미",
		"cardid":46264,
		"cardid_original":46264,
		"health":30,
		"stage":[3,4,5],
		"weight":1,
		"tog":"스터미가 조그만 밀랍 친구 만든다! 스터미는 코볼트 파티 엄청 재미있게 해준다.",
		"desc":"이 코볼트는 양초를 이용해 자유자재로 하수인을 만들 수 있습니다.",
		"power":"(1) 밀랍 조각: 하수인 하나를 복사하여 1/1 하수인으로 소환합니다."
	}, 
	{
		"id":"boss012",
		"name_en":"a. f. kay",
		"name":"A. F. 케이",
		"cardid":47495,
		"cardid_original":47495,
		"health":40,
		"stage":[4],
		"weight":1,
		"tog":"인간 잡아라! 정신 딴 데 파는 동안!",
		"desc":"이 모험가가 한눈을 파는 사이에 공격하세요!",
		"power":"(2) 자리비움: 아무 행동도 하지 않습니다."
	}, 
	{
		"id":"boss013",
		"name_en":"gutmook",
		"name":"거트무크",
		"cardid":46329,
		"cardid_original":46329,
		"health":30,
		"stage":[4,5],
		"weight":1,
		"tog":"트로그. 퉷. 더는 말 안 한다. 하수인들로 뭉개 준다.",
		"desc":"이 늙은 트로그와 하수인들은 마력의 원천만 보면 벌떼같이 몰려갑니다.",
		"power":"(지속) 마법 소화: 상대편이 주문을 시전할 때마다 땅굴 트로그를 하나 소환합니다."
	}, 
	{
		"id":"boss014",
		"name_en":"blackseed",
		"name":"검은씨앗",
		"cardid":46279,
		"cardid_original":46279,
		"health":40,
		"stage":[4,5],
		"weight":1,
		"tog":"검은 씨앗이 깊고 싶은 곳에서… 비장의… 꾸웨엑… 꼬부랑 촉수 달고 나온다.",
		"desc":"이 펄볼그는 암흑 마법으로 미궁에 사는 생물의 모습을 뒤틀어 버립니다.",
		"power":"(0) 진화술: 하수인 하나를 비용이 (1) 높은 무작위 하수인으로 변신시킵니다."
	}, 
	{
		"id":"boss015",
		"name_en":"fungalmancer flurgl",
		"name":"곰팡이술사 플러글",
		"cardid":47320,
		"cardid_original":47320,
		"health":30,
		"stage":[4,5],
		"weight":1,
		"tog":"코볼트는 멀록 이해 못한다. 멀록은 말을 말같이 않게 말한다.",
		"desc":"이 곰팡이술사는 하수인들에게 힘을 불어넣습니다. 곰팡이로요.",
		"power":"(2) 곰팡이 감염: 내 하수인들에게 +1/+1을 부여합니다."
	}, 
	{
		"id":"boss016",
		"name_en":"lyris the wild mage",
		"name":"광기의 마법사 리리스",
		"cardid":46371,
		"cardid_original":46371,
		"health":40,
		"stage":[4,5],
		"weight":1,
		"tog":"미친 엘프가 반짝이 날린다! 교활한 뱀 같은 거 만드는 불쟁이는 조심해야 된다.",
		"desc":"불을 좋아합니다. 불을 좋아하는 주인을 하수인들도 좋아합니다.",
		"power":"(1) 비전 주입: '신비한 화살' 카드 1장을 내 손으로 가져옵니다."
	}, 
	{
		"id":"boss017",
		"name_en":"thaddock the thief",
		"name":"도둑 타도크",
		"cardid":46321,
		"cardid_original":46321,
		"health":40,
		"stage":[4,5],
		"weight":1,
		"desc":"타도크의 하수인이 저기 보이나 싶더니... 사라집니다!",
		"power":"(1) 전략적 후퇴: 아군 하수인 하나를 내 손으로 다시 가져옵니다."
	}, 
	{
		"id":"boss018",
		"name_en":"whompwhisker",
		"name":"묵사발수염",
		"cardid":47303,
		"cardid_original":47303,
		"health":40,
		"stage":[4,5],
		"weight":1,
		"tog":"내 친구 묵사발수염은 코볼트에서 제일 뿔났다. 흐흐.",
		"desc":"절대 홀로 싸우지 않는 코볼트 광전사입니다.",
		"power":"(2) 참전: 두 플레이어 모두 하수인을 하나씩 소집합니다."
	}, 
	{
		"id":"boss019",
		"name_en":"mushhuckster max",
		"name":"버섯상인 맥스",
		"cardid":47361,
		"cardid_original":47361,
		"health":40,
		"stage":[4,5],
		"weight":1,
		"tog":"버섯상인 맥스는 미궁의 나쁜 쪽을 맡고 있다.",
		"desc":"이 자가 파는 물약을 사고 싶진 않을 겁니다.",
		"power":"(2) 버섯이 왔어요: 원하는 버섯 물약을 직접 만듭니다."
	}, 
	{
		"id":"boss020",
		"name_en":"spiritspeaker azun",
		"name":"영매 아준",
		"cardid":46337,
		"cardid_original":46337,
		"health":40,
		"stage":[4,5],
		"weight":1,
		"tog":"트롤 우두머리가 있어야 미궁의 먹이사슬이 안정된다.",
		"desc":"이 트롤 사제는 죽은 자와 대화를 합니다... 두 번씩 말이죠.",
		"power":"(지속) 죽은 자의 토템: 모든 죽음의 메아리 능력이 2번 발동합니다."
	}, 
	{
		"id":"boss021",
		"name_en":"brimstone warden",
		"name":"유황 감시자",
		"cardid":46339,
		"cardid_original":46339,
		"health":30,
		"stage":[4],
		"weight":1,
		"tog":"쉬이이잇! 동상이라도 눈알, 막, 깜빡인다! 깨우지 마!",
		"desc":"고대의 수호자들을 깨우는 것만은 무슨 수를 써서든 막으세요…",
		"power":"(5) 해제의 수호물: 내 하수인들을 침묵 시킵니다."
	}, 
	{
		"id":"boss022",
		"name_en":"russell the bard",
		"name":"음유시인 러셀",
		"cardid":47365,
		"cardid_original":47365,
		"health":30,
		"stage":[4,5],
		"weight":1,
		"tog":"음유시인은 노래 부르면서 다른 온 세상 사람들 얼굴 공격한다.",
		"desc":"러셀의 선율은 귀에 쏙 들어오지요. 하수인들이 잘 알 겁니다.",
		"power":"(2) 유혹의 선율: 공격력이 2 이하인 적 하수인 하나를 가져옵니다."
	}, 
	{
		"id":"boss023",
		"name_en":"elder jari",
		"name":"장로 야리",
		"cardid":47305,
		"cardid_original":47305,
		"health":30,
		"stage":[4,5],
		"weight":1,
		"desc":"비전 마력을 모아 스스로를 방어하는 덩치 큰 펄볼그입니다.",
		"power":"(1) 신비의 방볍: 방어도를 +3 얻습니다."
	}, 
	{
		"id":"boss024",
		"name_en":"battlecrier jin'zo",
		"name":"전투의 함성가 진조",
		"cardid":46338,
		"cardid_original":46338,
		"health":40,
		"stage":[4,5],
		"weight":1,
		"desc":"진조의 함성은 두 번 울려퍼집니다.",
		"power":"(지속) 전투 토템: 모든 전투의 함성 능력이 2번 발동합니다."
	}, 
	{
		"id":"boss025",
		"name_en":"kraxx",
		"name":"크락스",
		"cardid":47258,
		"cardid_original":47258,
		"health":30,
		"stage":[4,5],
		"weight":1,
		"desc":"이 고대의 바위 수호자는 보물들이 여기 그대로 있기를 바랍니다.",
		"power":"(2) 거인의 발 구르기: 모든 적 하수인에게 피해를 1 줍니다."
	}, 
	{
		"id":"boss026",
		"name_en":"overseer mogark",
		"name":"감독관 모가르크",
		"cardid":46311,
		"cardid_original":46313,
		"health":60,
		"stage":[5,6,7],
		"weight":1,
		"desc":"부하들에게 지나친 \"동기부여\"를 하는 트로그 사령관입니다.",
		"power":"(1) 이글거리는 채찍: 아군 하수인에게 피해를 1 주고 공격력을 +5 부여합니다."
	}, 
	{
		"id":"boss027",
		"name_en":"pathmaker hamm",
		"name":"폭탄마 햄",
		"cardid":46270,
		"cardid_original":46270,
		"health":60,
		"stage":[5,6,7],
		"weight":1,
		"desc":"코볼트가 땅굴을 파는 방법은 한 가지가 아닙니다.",
		"power":"(2) 불안정한 폭파: 무작위 적 셋에게 피해를 2 줍니다."
	}, 
	{
		"id":"boss028",
		"name_en":"gnosh the greatworm",
		"name":"거대벌레 노쉬",
		"cardid":46243,
		"cardid_original":46243,
		"health":40,
		"stage":[6],
		"weight":1,
		"tog":"이거 동굴 아니고 입이다! 엄청 큰 입! 이빨 가득한 입!",
		"desc":"언제나 가장 크고 맛있는 하수인을 잡아먹습니다.",
		"power":"(2) 꿀꺽 삼키기: 공격력이 가장 높은 하수인을 처치합니다."
	}, 
	{
		"id":"boss029",
		"name_en":"gutmook",
		"name":"거트무크",
		"cardid":46330,
		"cardid_original":46330,
		"health":50,
		"stage":[6,7],
		"weight":1,
		"tog":"트로그. 퉷. 더는 말 안 한다. 하수인들로 뭉개 준다.",
		"desc":"이 늙은 트로그와 하수인들은 마력의 원천만 보면 벌떼같이 몰려갑니다.",
		"power":"(지속) 마법 흡수: 상대편이 주문을 시전할 때마다 카드를 1장 뽑습니다. 그 카드의 비용이 (1)이 됩니다."
	}, 
	{
		"id":"boss030",
		"name_en":"blackseed",
		"name":"검은씨앗",
		"cardid":46281,
		"cardid_original":46281,
		"health":60,
		"stage":[6,7],
		"weight":1,
		"tog":"검은 씨앗이 깊고 싶은 곳에서… 비장의… 꾸웨엑… 꼬부랑 촉수 달고 나온다.",
		"desc":"이 펄볼그는 암흑 마법으로 미궁에 사는 생물의 모습을 뒤틀어 버립니다.",
		"power":"(1) 상급 진화: 하수인 하나를 비용이 (3) 높은 무작위 하수인으로 변신시킵니다."
	}, 
	{
		"id":"boss031",
		"name_en":"waxmancer sturmi",
		"name":"밀랍술사 스터미",
		"cardid":46264,
		"cardid_original":46266,
		"health":50,
		"stage":[6,7],
		"weight":1,
		"tog":"스터미가 조그만 밀랍 친구 만든다! 스터미는 코볼트 파티 엄청 재미있게 해준다.",
		"desc":"이 코볼트는 양초를 이용해 자유자재로 하수인을 만들 수 있습니다.",
		"power":"(3) 조각 경화: 하수인 하나를 복사하여 소환합니다."
	}, 
	{
		"id":"boss032",
		"name_en":"treasure vault",
		"name":"보물창고",
		"cardid":47465,
		"cardid_original":47465,
		"health":0,
		"stage":[6,7],
		"weight":1,
		"reward":"보물창고",
		"desc":"가능한 한 빨리, 최대한 많이 챙기십시오!",
		"power":"(5) 닫히는 문: 게임을 끝냅니다."
	}, 
	{
		"id":"boss033",
		"name_en":"voodoomaster vex",
		"name":"부두장인 벡스",
		"cardid":47001,
		"cardid_original":47001,
		"health":50,
		"stage":[6,7],
		"weight":1,
		"desc":"트롤이 되고 싶어합니다. 전투의 함성을 지르고 죽음의 메아리를 들으면서 말이죠.",
		"power":"(0) 혼돈의 토템: 모든 전투의 함성과 죽음의 메아리 능력이 2번 발동합니다."
	}, 
	{
		"id":"boss034",
		"name_en":"bristlesnarl",
		"name":"뾰족털뭉치",
		"cardid":46341,
		"cardid_original":46341,
		"health":50,
		"stage":[6,7],
		"weight":1,
		"desc":"순식간에 덩치 큰 친구들을 불러낼 수 있는 전설의 펄볼그 사냥꾼입니다.",
		"power":"(3) 사냥꾼의 부름: 내 손에 있는 카드들의 비용이 (1) 감소합니다."
	}, 
	{
		"id":"boss035",
		"name_en":"tad",
		"name":"옳챙이",
		"cardid":46340,
		"cardid_original":46340,
		"health":20,
		"stage":[6],
		"weight":0.5,
		"reward":"옳챙이의 낚싯대",
		"desc":"그저 낚시가 하고 싶은 멀록일 뿐이에요, 알겠어요?",
		"power":"(0) 월척이다옳! 내 덱에서 무작위 하수인을 하나 소환합니다."
	}, 
	{
		"id":"boss036",
		"name_en":"lava-filled chamber",
		"name":"용암의 방",
		"cardid":47322,
		"cardid_original":47322,
		"health":50,
		"stage":[6,7],
		"weight":1,
		"desc":"코볼트들은 용암이 넘쳐흐르는 이곳을 널빤지로 막아보려 합니다!",
		"power":"(지속) 바닥을 피해라: 하수인을 낸 후에 그 하수인에게 피해를 2 줍니다."
	}, 
	{
		"id":"boss037",
		"name_en":"ixlid",
		"name":"익슬리드",
		"cardid":46361,
		"cardid_original":46361,
		"health":20,
		"stage":[6],
		"weight":1,
		"desc":"치명적인 포자는 모험가를 단숨에 쓰러뜨릴 수도 있습니다!",
		"power":"(2) 포자 발아: 굉장히 치명적인 포자를 하나 소환합니다."
	}, 
	{
		"id":"boss038",
		"name_en":"george and karl",
		"name":"조지와 칼",
		"cardid":46323,
		"cardid_original":46323,
		"health":30,
		"stage":[6],
		"weight":1,
		"tog":"이 둘은 어느 날 밀림에서 굴러들어왔다.",
		"desc":"운고로에서 행방불명된 성기사 2인조입니다.",
		"power":"(2) 신앙: 내 하수인들에게 천상의 보호막을 부여합니다."
	}, 
	{
		"id":"boss039",
		"name_en":"candlebeard",
		"name":"촛불수염",
		"cardid":46318,
		"cardid_original":46318,
		"health":60,
		"stage":[6,7],
		"weight":1,
		"tog":"촛불수염은 보물 찾으면 코볼트가 해적이 될줄 알고 있다.",
		"desc":"이 코볼트 해적이 가장 좋아하는 가수는 전진이라고 하네요.",
		"power":"(지속) 돌지이이이인!: 내 하수인을 낸 후에, 그 하수인에게 돌진을 부여합니다."
	}, 
	{
		"id":"boss040",
		"name_en":"trapped room",
		"name":"함정의 방",
		"cardid":47328,
		"cardid_original":47328,
		"health":40,
		"stage":[6,7],
		"weight":1,
		"tog":"쉬잇… 아무것도 건드리면 안 된다…",
		"desc":"발 밑을 조심하세요. 아무것도... 건드리지 마세요!",
		"power":"(지속) 경보: 내 비밀이 밝혀질 때마다 3/3 톱날을 하나 소환합니다."
	}, 
	{
		"id":"boss041",
		"name_en":"chronomancer inara",
		"name":"시간술사 이나라",
		"cardid":47475,
		"cardid_original":47475,
		"health":50,
		"stage":[7],
		"weight":1,
		"desc":"이나라가 힘을 모으기 시작하면, 시간 조종 능력을 조심하십시오!",
		"power":"(10) 시간 훔치기: 내 마나를 3개 파괴합니다. 내 턴이 한 번 더 진행됩니다."
	}, 
	{
		"id":"boss042",
		"name_en":"the mothergloop",
		"name":"점액어미",
		"cardid":46344,
		"cardid_original":46344,
		"health":50,
		"stage":[7],
		"weight":1,
		"desc":"끈적한 친구들에게 압도되지 않도록 조심하세요.",
		"power":"(2) 점액: 내 손에 있는 하수인들에게 +1/+1을 부여합니다."
	}, 
	{
		"id":"boss043",
		"name_en":"jeeru",
		"name":"지루",
		"cardid":47307,
		"cardid_original":47307,
		"health":40,
		"stage":[7],
		"weight":1,
		"tog":"악 안돼, 안 돼, 등불 문지르지 말라고! 알쏭달쏭 함정이다.",
		"desc":"등불을 문지르지 마세요! 이미 문질렀나요?",
		"power":"(1) 세 개의 작은 소원: 각 플레이어가 카드를 3장씩 뽑습니다."
	}, 
	{
		"id":"boss044",
		"name_en":"vustrasz the ancient",
		"name":"고대의 부스트라즈",
		"cardid":46349,
		"cardid_original":46349,
		"health":70,
		"stage":[8],
		"weight":1,
		"tog":"너, 용 보물 훔쳐 갈 거냐? 오오우, 용이 어어엄청 화낼 거다…",
		"desc":"그의 어마어마한 보물 상자를 마음껏 가져가 보세요... 보복이 두렵지 않다면요!",
		"power":"(0) 보복의 숨결: 없어진 보물 상자 하나당 모든 적에게 피해를 1 줍니다."
	}, 
	{
		"id":"boss045",
		"name_en":"xol the unscathed",
		"name":"다치지 않는 솔",
		"cardid":47410,
		"cardid_original":47410,
		"health":70,
		"stage":[8],
		"weight":1,
		"tog":"솔의 눈은 쳐다보지 마라! 그 큰 머리에 눈알들이 엄청 달렸다.",
		"desc":"당신에게 눈독을 들이고 있습니다. 모든 눈으로요.",
		"power":"(지속) 광선 주세요!: 내 턴이 끝날 때 광선 카드 1장을 내 손으로 가져옵니다."
	}, 
	{
		"id":"boss046",
		"name_en":"king togwaggle",
		"name":"미궁왕 토그왜글",
		"cardid":47210,
		"cardid_original":47210,
		"health":70,
		"stage":[8],
		"weight":1,
		"tog":"내 차례다. 흐핫! 나는 네가 쓸어 모은 전리품 머리부터 발끝까지 다 쓸어 간다!",
		"desc":"조심하세요! 쓰러진 모험가들의 전리품을 잔뜩 지니고 있습니다.",
		"power":"(3) 마법 양초: 보물을 찾습니다!"
	}, 
	{
		"id":"boss047",
		"name_en":"the darkness",
		"name":"어둠의 존재",
		"cardid":47333,
		"cardid_original":47333,
		"health":70,
		"stage":[8],
		"weight":1,
		"tog":"어둠의 존재 제일 무서워해라! 코볼트가 쟤 때문에 양초 들고다닌다.",
		"desc":"코볼트들이 양초를 가지고 다니는 데에는 이유가 있습니다.",
		"power":"(0) 밀려오는 어둠: 5/5 어둠의 정령을 하나 소환합니다."
	}, 
	{
		"id":"boss048",
		"name_en":"azari, the devourer",
		"name":"포식자 아자리",
		"cardid":46352,
		"cardid_original":46352,
		"health":70,
		"stage":[8],
		"weight":1,
		"tog":"포식자가 풀려났다! 모두 도망쳐!",
		"desc":"악마 중에서도 가장 끔찍한 녀석이 풀려났습니다! 그리고 굉장히 굶주려 있고요.",
		"power":"(0) 집어삼키기: 상대편의 다음 카드 2장을 없앱니다."
	}
];
